### ISSUE TITLE
docker-plugin installed but inactive

### ISSUE THREAD

**Issue by rolele** [ClusterHQ/ansible-role-flocker#6]
after running the role:

```

---
- hosts: all
  vars:
    flocker_control_service_groupname: flocker_control_service
    flocker_agents_groupname: flocker_agents
    flocker_cluster_name: my_flocker_cluster
    flocker_install_docker_plugin: true
    flocker_agent_yml_path: /Users/others/ansible/project/ansible/group_vars/agent.yml 
  roles:
    - role: ClusterHQ.flocker
```

Installed is ok but if I check the status of the services (it is inactive)

```
[root@manager1 vagrant]# systemctl status flocker-container-agent
    ● flocker-container-agent.service - Flocker Container Agent
       Loaded: loaded (/usr/lib/systemd/system/flocker-container-agent.service; disabled; vendor preset: disabled)
       Active: active (running) since Fri 2016-10-14 02:57:56 BST; 760ms ago
     Main PID: 17032 (flocker-contain)
       Memory: 23.2M
       CGroup: /system.slice/flocker-container-agent.service
               └─17032 /opt/flocker/bin/python /usr/sbin/flocker-container-agent --journald

    Oct 14 02:57:56 manager1 systemd[1]: Started Flocker Container Agent.
    Oct 14 02:57:56 manager1 systemd[1]: Starting Flocker Container Agent...
    [root@manager1 vagrant]# systemctl status flocker-docker-plugin
    ● flocker-docker-plugin.service - Flocker Docker Plugin
       Loaded: loaded (/usr/lib/systemd/system/flocker-docker-plugin.service; disabled; vendor preset: disabled)
       Active: inactive (dead)
```

I neet to enable and restart the service manually

```
    [root@manager1 vagrant]# systemctl enable flocker-docker-plugin
    Created symlink from /etc/systemd/system/multi-user.target.wants/flocker-docker-plugin.service to /usr/lib/systemd/system/flocker-docker-plugin.service.

    [root@manager1 vagrant]# systemctl status flocker-docker-plugin
    ● flocker-docker-plugin.service - Flocker Docker Plugin
       Loaded: loaded (/usr/lib/systemd/system/flocker-docker-plugin.service; enabled; vendor preset: disabled)
       Active: inactive (dead)

    [root@manager1 vagrant]# systemctl restart flocker-docker-plugin
```

now the docker plugin is active

```
 [root@manager1 vagrant]# systemctl status flocker-docker-plugin
    ● flocker-docker-plugin.service - Flocker Docker Plugin
       Loaded: loaded (/usr/lib/systemd/system/flocker-docker-plugin.service; enabled; vendor preset: disabled)
       Active: active (running) since Fri 2016-10-14 02:59:40 BST; 1s ago
     Main PID: 17973 (flocker-docker-)
       Memory: 43.9M
       CGroup: /system.slice/flocker-docker-plugin.service
               └─17973 /opt/flocker/bin/python /usr/sbin/flocker-docker-plugin --journald

    Oct 14 02:59:40 manager1 systemd[1]: flocker-docker-plugin.service holdoff time over, scheduling restart.
    Oct 14 02:59:40 manager1 systemd[1]: Started Flocker Docker Plugin.
    Oct 14 02:59:40 manager1 systemd[1]: Starting Flocker Docker Plugin...
```

I am running CentOS Linux release 7.2.1511 (Core)

**Comment by rolele** [comment]
I solved this. I was doing it wrong. I write the solution here just in case it can help someone in the future.
to debug this on centos I was able to get the logs of the services using:

```
journalctl -u flocker-dataset-agent --since "1 hour ago" -l --no-pager|less
journalctl -u flocker-docker-plugin --since "1 hour ago" -l --no-pager|less
```

I was missing plugin.crt in /ect/flocker
need to be generated using `flocker-ca create-api-certificate plugin`

agent.ml was badly formatted, here is the working version

```
version: 1
control-service:
  hostname: "192.168.77.21"
dataset:
  backend: "loopback"
  root_path: "/var/lib/flocker/loopback"
```

I was missing some unusable vars

```
---
- hosts: all
  vars:
    flocker_control_service_groupname: flocker_control_service
    flocker_agents_groupname: flocker_agents
    flocker_cluster_name: my_flocker_cluster
    flocker_install_docker_plugin: true
    flocker_api_cert_name: plugin
    flocker_local_tempdir: /tmp/{{ flocker_cluster_name }}
    flocker_agent_yml_path: /Users/others/ansible/project/ansible/group_vars/agent.yml 
  roles:
    - role: ClusterHQ.flocker
```
